# SPDX-License-Identifier: Apache-2.0
auth:
  enabled: true
  password: test-password

acl:
  enabled: true
  rules: |
    topic readwrite #

broker:
  tls:
    enabled: true
    certSecretName: mosquitto-tls
    caFile: ca.crt
    requireCertificate: true
    useIdentityAsUsername: true

service:
  type: LoadBalancer

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mosquitto-tls
    type: kubernetes.io/tls
    stringData:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDFTCCAf2gAwIBAgIUY+E+hXWDaS/tI3f25z0/tO4QgpswDQYJKoZIhvcNAQEL
        BQAwGjEYMBYGA1UEAwwPbW9zcXVpdHRvLmxvY2FsMB4XDTI2MDYxNTIxMTAxOVoX
        DTM2MDYxMjIxMTAxOVowGjEYMBYGA1UEAwwPbW9zcXVpdHRvLmxvY2FsMIIBIjAN
        BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1KIfZm9vLrlSZnOm18PL7xzc3yc7
        vAcq0RAxNkwB5l44iL5AoEyxSMfvpfJlBoMoMOL8sKXiq1biXzBh+8G82p//ORyf
        of+RZkJNFhMZt08oGlWOo0Zt9HCQRDREpwsFicXtxXUv9UveBl4430b54zqa2XeZ
        9PLj7pbFX7nKcryvOlWBW6to5cMmm4nMwx/lGiOlS2+4iQn9jgPqvPkHbcq0AZnt
        2Qg5hUeU3s9fdO6kd2W8WG7PSY8JyWIaAMcKXX7dtv96LwnPQE4zGo1A7JIGWKZS
        TNBN0Le3GMZL6wxX7YYoM1fsgJP4nq5AqjRhUBxezONND0jLQqnpnBA2/wIDAQAB
        o1MwUTAdBgNVHQ4EFgQU1kSNUYANYpWt64KywNwoiVpjMFUwHwYDVR0jBBgwFoAU
        1kSNUYANYpWt64KywNwoiVpjMFUwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
        AQsFAAOCAQEAXAoEumQ6di/zi6A72jIGvtw+4Xvy4ysE3mBPAxec/cTakHSpxLG1
        sA1Yqo3wpg8kG1GmcL7e3pJyV2UkH9hxcuEdHsipQEoUI2LYkCkIK7eN53mZezxO
        eOmsQmM2uVCqH/Uzav6es9U16K3BvT4RlxWtJh0bDYjVlaKZF7diqNXWMYnhWhp6
        Pw0zuED33bpld3u0sZsV+g7ADEzPgUlWsvqtGfpeAI2jxNdtjS3jWgkHSyhXfmP2
        3NOqa8a5WjhwpSvluOyfjZjfJd6uc7XtaP6TxyMilHvov8UbezIPeVk8ZtTEsyMb
        lhytMO8G0oIp/NoYKyhmu8+e4e6mUxKxuQ==
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUoh9mb28uuVJm
        c6bXw8vvHNzfJzu8ByrREDE2TAHmXjiIvkCgTLFIx++l8mUGgygw4vywpeKrVuJf
        MGH7wbzan/85HJ+h/5FmQk0WExm3TygaVY6jRm30cJBENESnCwWJxe3FdS/1S94G
        XjjfRvnjOprZd5n08uPulsVfucpyvK86VYFbq2jlwyabiczDH+UaI6VLb7iJCf2O
        A+q8+QdtyrQBme3ZCDmFR5Tez1907qR3ZbxYbs9JjwnJYhoAxwpdft22/3ovCc9A
        TjMajUDskgZYplJM0E3Qt7cYxkvrDFfthigzV+yAk/ierkCqNGFQHF7M400PSMtC
        qemcEDb/AgMBAAECggEAEBtx3nwdg4AVXl5vapPR7HyWvK7HpyAx3aFo4PCUCkPj
        63PiCGKW4WkH3d3FSl+AGWfwdV8zkwAjaMuM+Jm9+R+6oTRqYUavWHw4Q65RueGc
        q5YElpi8tpIaU5hUBQVgN4YPU3BjoCTNnlTf4QYK4uwrE8MsHfKSUp4IOI6l59gA
        0TFEYmmjbCx8VtYM9SUjfW9nDQlUyaxseuhaNDuZidA7fLJ85vqKHGWDjTrJ3DXZ
        H/sy1h7rz2AWMu3bmTevfuui9ytDBGJ6tqjq4pQN2bG5L1t1BzXmlHoQjoKKdxva
        +qeqz0SS0lJI7y8RsJy+zsePfaJKptbZMONwFD12NQKBgQD4dd3IxVw2YvpQEjRO
        Die6pPVTK/nvDuHKv8NNORdtfwMHyLkm1ecuIJH6gcKWpfEu/pQQEsNX05BxwkJI
        q5WNVkFOAmbx/F6TOitqZggFdKmL1DFf5KUT0ml1j1UgZOidMu6a6VtAmD3bjXIi
        WfNDsI+vtwbEQobsPACqimNCwwKBgQDbFfASiPPbPrI5wkTFuqmZEDG5kVL9LAYA
        kCzpSYS+FcaZot+crZwTnxoBQEjG5pIh6vhA+O0WjYot9JvvmSSPYV8InLwaYVy4
        USHNS3UluHB29IdI2U7/md+KtJJ1DK9QefJCL7G9x9gf0+WSOYr2Z+qfmwQzJEpx
        R/aFFi9/FQKBgAbCdik7LVoRcUvyYtfozK3oRQBhRuh5GC2C8BZOwlNpTDTPAjKL
        SUHZAv+0vg2JMDmeFXsmd4gRKnHd3h3KBUSWHyq3KAPXYN9SitHXOsqjNOWn/Tvl
        pZQXemUHZEKAXE/CjflK9f+Y5L3vaDaFCfhCenZGXXnDcZZFv6LkJvUvAoGBAMa9
        mOGHgQdjUZQZyf9AvHcQfLskvI7Tr8I1B7i8q4EwCc/3MzhTOSGHk7SM1zgvk2LX
        X0q5RYHO9gmIOyjX2JWEtAwA+pZHui+t0acFC4kjTkpquop4LzSpJmMSOUWbMzIi
        3YPy9h79ue3tb/T85DVwwSL2IZIvGqS2rke+f2mdAoGBANAIU0JJxmcKqfMVMciP
        J2xkm77w8x3Sqdx+b4v/BJ85+DjUY0KTDyhhGVgtv7OGXt6oFXOrh038Yn5k3D+2
        bLuwWIwQOFlhkC3ccfGL6j0BQ0B6MnXArPbv4HQXcKqnV6POxN2ZiZaMRLMu6JMf
        slRUiHUXYu8o/Ku1PVH6Ii5n
        -----END PRIVATE KEY-----
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDFTCCAf2gAwIBAgIUY+E+hXWDaS/tI3f25z0/tO4QgpswDQYJKoZIhvcNAQEL
        BQAwGjEYMBYGA1UEAwwPbW9zcXVpdHRvLmxvY2FsMB4XDTI2MDYxNTIxMTAxOVoX
        DTM2MDYxMjIxMTAxOVowGjEYMBYGA1UEAwwPbW9zcXVpdHRvLmxvY2FsMIIBIjAN
        BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1KIfZm9vLrlSZnOm18PL7xzc3yc7
        vAcq0RAxNkwB5l44iL5AoEyxSMfvpfJlBoMoMOL8sKXiq1biXzBh+8G82p//ORyf
        of+RZkJNFhMZt08oGlWOo0Zt9HCQRDREpwsFicXtxXUv9UveBl4430b54zqa2XeZ
        9PLj7pbFX7nKcryvOlWBW6to5cMmm4nMwx/lGiOlS2+4iQn9jgPqvPkHbcq0AZnt
        2Qg5hUeU3s9fdO6kd2W8WG7PSY8JyWIaAMcKXX7dtv96LwnPQE4zGo1A7JIGWKZS
        TNBN0Le3GMZL6wxX7YYoM1fsgJP4nq5AqjRhUBxezONND0jLQqnpnBA2/wIDAQAB
        o1MwUTAdBgNVHQ4EFgQU1kSNUYANYpWt64KywNwoiVpjMFUwHwYDVR0jBBgwFoAU
        1kSNUYANYpWt64KywNwoiVpjMFUwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
        AQsFAAOCAQEAXAoEumQ6di/zi6A72jIGvtw+4Xvy4ysE3mBPAxec/cTakHSpxLG1
        sA1Yqo3wpg8kG1GmcL7e3pJyV2UkH9hxcuEdHsipQEoUI2LYkCkIK7eN53mZezxO
        eOmsQmM2uVCqH/Uzav6es9U16K3BvT4RlxWtJh0bDYjVlaKZF7diqNXWMYnhWhp6
        Pw0zuED33bpld3u0sZsV+g7ADEzPgUlWsvqtGfpeAI2jxNdtjS3jWgkHSyhXfmP2
        3NOqa8a5WjhwpSvluOyfjZjfJd6uc7XtaP6TxyMilHvov8UbezIPeVk8ZtTEsyMb
        lhytMO8G0oIp/NoYKyhmu8+e4e6mUxKxuQ==
        -----END CERTIFICATE-----
