{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.acl.enabled (not .Values.acl.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.aclConfigMapName" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  {{ .Values.acl.existingConfigMapKey }}: |
    {{- .Values.acl.rules | nindent 4 }}
{{- end }}
