{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: broker
{{- end }}
