{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.authSecretName" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretUsernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.existingSecretPasswordKey }}: {{ default (randAlphaNum 24) .Values.auth.password | quote }}
{{- end }}
