{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if gt (len .Values.service.externalIPs) 0 }}
  externalIPs:
    {{- .Values.service.externalIPs | toYaml | nindent 4 }}
  {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
  ports:
    {{- if not .Values.broker.tls.enabled }}
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
      {{- if ne (int .Values.service.mqttNodePort) 0 }}
      nodePort: {{ .Values.service.mqttNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.broker.listeners.websocketEnabled }}
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      {{- if ne (int .Values.service.websocketNodePort) 0 }}
      nodePort: {{ .Values.service.websocketNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.broker.tls.enabled }}
    - name: mqtts
      port: {{ .Values.service.mqttsPort }}
      targetPort: mqtts
      protocol: TCP
      {{- if ne (int .Values.service.mqttsNodePort) 0 }}
      nodePort: {{ .Values.service.mqttsNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.monitoring.sidecar.enabled }}
    - name: prometheus
      port: {{ .Values.monitoring.sidecar.port }}
    {{- if .Values.monitoring.sidecar.nodePort }}
      nodePort: {{ .Values.monitoring.sidecar.nodePort }}
    {{- end }}
      targetPort: prometheus
      protocol: TCP
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.headlessServiceName" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: broker
  ports:
    {{- if not .Values.broker.tls.enabled }}
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
    {{- end }}
    {{- if .Values.broker.listeners.websocketEnabled }}
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
    {{- end }}
    {{- if .Values.broker.tls.enabled }}
    - name: mqtts
      port: {{ .Values.service.mqttsPort }}
      targetPort: mqtts
      protocol: TCP
    {{- end }}
