apiVersion: v2
appVersion: v1.13.0
description: Real-time infrastructure for developers. LiveKit is the open source stack
  for streaming audio, video, and data.
name: livekit-server
sources:
- https://github.com/livekit/livekit
type: application
version: 1.13.0
