annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/changes: |
    - kind: added
      description: "allow custom probe ports (#588)"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Official Website
      url: https://mosquitto.org
    - name: Documentation
      url: https://helmforge.dev/docs/charts/mosquitto
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/mosquitto
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/maturity: stable
  helmforge.dev/repository: https://repo.helmforge.dev
  helmforge.dev/signed: gpg+cosign
apiVersion: v2
appVersion: 2.0.22
description: A Helm chart for deploying Eclipse Mosquitto with WebSocket support and
  optional MQTTX Web
home: https://helmforge.dev
icon: https://helmforge.dev/icons/charts/mosquitto.png
keywords:
- mosquitto
- mqtt
- broker
- websocket
- mqttx
kubeVersion: '>=1.26.0-0'
maintainers:
- name: helmforgedev
- name: mberlofa
name: mosquitto
sources:
- https://github.com/helmforgedev/charts
- https://hub.docker.com/_/eclipse-mosquitto
- https://github.com/eclipse-mosquitto/mosquitto
type: application
version: 1.5.0
